### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Kaiser-Katana** [016/lm180_iEVE_Echoes#13]
For Egnlish users, we are looking for translator, do things like check typo on iEVE and do special translate later, if you find any typo just report a bug thx.

You are also welcome to help us share the iEVE website to English user, to be honest, we dont't know how to promote in English users, thx again.

Here the correct text:
For english users, we are looking for translators, do things like check typo on iEVE and do special translate later, if you find any typo just report a bug thx.

You are also welcome to help us share the iEVE website to english users, to be honest, we dont't know how to promote in english, thx again.

**Comment by 016** [comment]
fixed thx.
