### ISSUE TITLE
中文 矿石文字错误

### ISSUE THREAD

**Issue by lone-wuwa** [016/lm180_iEVE_Echoes#14]
原矿名称为黑赭石 在iEVE中展示的是黑赫石

**Comment by lone-wuwa** [comment]
![1](https://user-images.githubusercontent.com/70455266/91648005-a99e3a80-ea94-11ea-9d7c-a23c27cb7c2b.png)

**Comment by lone-wuwa** [comment]
![image](https://user-images.githubusercontent.com/70455266/91648090-e61e6600-ea95-11ea-9b76-9d517c910906.png)

**Comment by 016** [comment]
@lone-wuwa 已修复，下一个版本更新，感谢支持
