### ISSUE TITLE
Materials page needs distinct sub-tabs with working URLs

### ISSUE THREAD

**Issue by Chtorr00** [016/lm180_iEVE_Echoes#15]
Hello. This is a tremendous resource. There is two small changes that could be made to make the website even more useful. 

On the Material Price page, you have separate sub-tabs for Miner, Planetary, Salvaged Material, etc. 

These have partially been differentiated as Tab_1. Tab_2, Tab_3, but when you click on the sub-tab to open in a new window, the new page does not render correctly. 

Ideally, each of these sub-tabs should have their own independent URL:
https://ieve.yiilib.com/#/material/tab_1
https://ieve.yiilib.com/#/material/tab_2 
https://ieve.yiilib.com/#/material/tab_3
etc

If the URL structure was changed, then automated data extraction tools in Excel could easily work with the data you have collected. If you ask users that re-use your data for an acknowledgement and a link back to your website, it might help promote the site more widely among English speakers. 

Also, adding a new tab for daily prices of the raw ores would be helpful. You are already collecting the price data, so it should be relatively easy to implement. 

Thanks!

**Comment by Vangor** [comment]
+100500 for this feature, really need something for extracting prices

**Comment by Narevau** [comment]
Agreed, that would be very useful! I would also love to see the prices updated every day and if no prices change to still change the date in the "update date" column.

**Comment by 016** [comment]
@Chtorr00 
first I will add the tab_x hash to support soon, it's already on my todo list now, after that you guys can direct use https://ieve.yiilib.com/#/material/tab_x to access page with data auto refresh.

Next, will add the Raw Ore soon, it's a good idea.

@Narevau unfortunately, we only update price twice/week, the reason is we don't have enough man to do it(right now I am a kind busy with dev, all data work are working by volunteers), if you want help, you are welcome to join us.

@Chtorr00 @Vangor @Narevau thank you for the feedback, let me know if u have any new idea.

**Comment by Vangor** [comment]
@016 I know one Russian corp that working on extracting prices from the client, and make automatization out of it. If you interested I can try to speak with them about giving out some API or a way to extract such data.

**Comment by Narevau** [comment]
I would be very interested in having access to such an API if that is possible.

**Comment by 016** [comment]
@Vangor @Chtorr00 @Narevau 
two things added
1. add Ore tab, show daily price for Ore, remember it's still update by manual
2. add hash support for diff type try with:
https://ieve.yiilib.com/#/material/0
https://ieve.yiilib.com/#/material/1
https://ieve.yiilib.com/#/material/2
https://ieve.yiilib.com/#/material/3
https://ieve.yiilib.com/#/material/11
https://ieve.yiilib.com/#/material/21

ps: still have some new idea for this page, I will do deep think when I have time, I was super busy in recent days, hope you guys love this change.
