### ISSUE TITLE
Orec prices

### ISSUE THREAD

**Issue by Vangor** [016/lm180_iEVE_Echoes#16]
Can the Miner tab also have prices for Ore?

**Comment by 016** [comment]
@Vangor which Miner tab do you mean, plz give me more info, let's see what we can do for it.

**Comment by Vangor** [comment]
@016 here https://ieve.yiilib.com/#/material - no prices for Ore

**Comment by Vangor** [comment]
Seems it's duplicate of https://github.com/016/lm180_iEVE_Echoes/issues/15 closing it
