### ISSUE TITLE
The ship build calculator leading 0 issue

### ISSUE THREAD

**Issue by evilwarlock** [016/lm180_iEVE_Echoes#18]
In the ship build calculator page, when put in the mats numbers with leading zeros, the sum of the number can't display correctly.

**Comment by 016** [comment]
@evilwarlock Hi, I can't repeat this one, can u plz give me more info like some steps? I will try repeat and fix it. thx.

**Comment by evilwarlock** [comment]
![7IW9_4_(4)`MK36XTZ3$OX2](https://user-images.githubusercontent.com/5721381/93294881-a39c9f00-f7a0-11ea-8fce-24825c67bbb5.png)

**Comment by 016** [comment]
![Screen Shot 2020-09-16 at 3 10 17 PM](https://user-images.githubusercontent.com/7589575/93310542-823ac200-f837-11ea-9389-4765d3b7cb77.jpg)
@evilwarlock fixed, honest I don't thinking use zero leading number is a good idea, but I fix it.
