### ISSUE TITLE
恳求好心人能做一个端游数据版

### ISSUE THREAD

**Issue by 1416565431** [016/lm180_iEVE_Echoes#3]
楼主如果能做一个端游数据版会造福很多人的，大家也都非常感谢你！

**Comment by 016** [comment]
@1416565431 Hey很高兴收到你的留言，但目前并没有向eve端游兼容的计划，原因如下：
1. 我并没有深入的接触过端游，而且端游的时间已经非常久远了，现在再去学习和掌握，不是很合适, 而且端游和手游很多地方的数据格式和种类也不一样
2. 正因为端游的时间久远，所以端游已经存在大量前辈做的各种工具，基本能满足现在玩家的需求，比如：eve空间站, ceve-market等
3. 相对于端游，手游会有机会吸引到 大量的新手用户，我的想法是通过这个工具，降低新手的入门门槛，争取让多一部分新手留下来
4. 个人原因，我是利用业余时间来做这个事情的，不瞒你说现在已经时间严重不够用了

so, 实在抱歉，感谢你对 ieve的支持和建议
