### ISSUE TITLE
Don't exceed 100%

### ISSUE THREAD

**Issue by Ledrap** [016/lm180_iEVE_Echoes#34]
In the ship builder tool. It would be useful that the calculation of "Required" stopped at 100% (even if "In Hand" is greater than "Build Cost". An ore/material that is at or greater than "Build Cost" should not show in "Ore Result" screen.

It would also be useful (but not essential - can open/configure multiple pages) that the configuration screen (Config Params) allowed saving of multiple configurations (manufacturers often have different efficiencies for different ship types - but mining settings stay the same for all manufacturing).

Thanks for the tool - very helpful

**Comment by 016** [comment]
Hey @Ledrap 

>>first part
`In the ship builder tool. It would be useful that the calculation of "Required" stopped at 100% (even if "In Hand" is greater than "Build Cost". An ore/material that is at or greater than "Build Cost" should not show in "Ore Result" screen.`

for the first part, we already did it, plz test again,

for the second part we will support it in the future it's good idea, we will do it in account setting, honest we want build in skill system, but we are waiting for API, if there is an api for loading account detail, then player don't need setting anything, just give a access auth, that's all

anyway, thx for you feedback, it's really good!

**Comment by Ledrap** [comment]
Thanks for the quick response and the feedback.

**Comment by Ledrap** [comment]
I notice that the ore that has already exceeded required amount does not show up in the Ore Result screen - but the Required column and Rate in Hand (on the Result screen) still calculate incorrectly (showing negative amounts and over 100%).

No big deal - just some testing feedback
[XC100 screen.pdf](https://github.com/016/lm180_iEVE_Echoes/files/5289953/XC100.screen.pdf)

**Comment by 016** [comment]
@Ledrap let me try to explain u this part, for example Noc 7141/6410.56/-730.44/111.39% in your demo pdf, 

-730.44 means this part will not use, so I added a negative sign before it.
111.39% means 11.39% for the second ship if u need

for people who only build one ship, this part data mean nothing, but we usually build more than 1, so this part is useful for me.

again thx for your feedback.
