### ISSUE TITLE
造船计算器材料效率导致的总价问题

### ISSUE THREAD

**Issue by Hertz52** [016/lm180_iEVE_Echoes#35]
材料效率越高，显示的总价反而越高，这是否合理？
谢谢
- by silo

100效率：
![100](https://user-images.githubusercontent.com/9529435/94104923-ca2a9c00-fe6a-11ea-989d-3f43e0dd9f53.png)
150效率：
![150](https://user-images.githubusercontent.com/9529435/94104909-c1d26100-fe6a-11ea-865b-47d945f1ece7.png)

**Comment by 016** [comment]
@Hertz52 这个是官方设置，你可以去游戏里看下，新建角色材料效率150%，通过学习技能 逐步减少，材料效率越低 所需材料越少， 如果非要说就是这个材料效率的翻译有点歧义吧，但是规则就是这样

**Comment by Hertz52** [comment]
多谢，明白了。
