### ISSUE TITLE
建议加上矿物的每立方单价

### ISSUE THREAD

**Issue by LabiKyo** [016/lm180_iEVE_Echoes#36]
对于挖矿效率是一个参考

**Comment by 016** [comment]
@LabiKyo 是个好主意 最近会增加这个功能， 刚从医院回来，效率有点低下，稍微等我下

**Comment by 016** [comment]
@LabiKyo 已添加， 欢迎试用， 我增加了2个立方单价，分别是原矿立方单价和提炼物立方单价， 价格根据我们更新的市场价格改变。

不得不说这个功能点很实用，在后面的使用中如果有其他想法请告诉我，谢谢
