### ISSUE TITLE
Some ship translations to english

### ISSUE THREAD

**Issue by nigel-gott** [016/lm180_iEVE_Echoes#4]
Hi, thanks for providing all these tools and data! [Here is a CSV file](https://pastebin.com/sfFn3uC7) with what I believe to be a number of missing translations for your website. I found these by cross referencing the actual ship data against other sources of English ship data, so I haven't manually checked every single one to be 100% sure. But I think it's certainly a starting place.

**Comment by 016** [comment]
Hi @nigel-gott , thx for the translate files, I will update the English ship names tonight, and it's really help thx again.

**Comment by nigel-gott** [comment]
Hey, saw your update with the English translations, looking good!

I cross-referenced the updated names against another dataset and think I have figured them all out now, with a number of fixes to incorrect translations in my first file above.

Also I noticed one error in the data itself:
- Probe Covert Ops Power Grid is currently 25, it should be 27 (proof https://youtu.be/YAPp7HZ7f48?t=140)

Here is the total dump of ship name translations, the 3rd column is the updated English names, the 4th column is True when the translation has been fixed. 

https://pastebin.com/SnuSC706

**Comment by 016** [comment]
Hey @nigel-gott , thx for the feedback, I will change the new names soon.

**Comment by 016** [comment]
back to Probe Covert Ops Power Grid data, we will update the data after 13 Aug, because they are still changing data, just wait plz, I will manual change the data to 27 for this ship now.

thx again for the support, let me know if u found anything else.
