### ISSUE TITLE
Make Ore constraints a checkbox

### ISSUE THREAD

**Issue by Ledrap** [016/lm180_iEVE_Echoes#45]
since it is a boolean it is much easier to check 'yes' than choose yes from a 2-answer drop down.

**Comment by 016** [comment]
Hey @Ledrap , it's a good idea, I will do it in recent days, was very busy in passed 2 weeks

**Comment by 016** [comment]
@Ledrap I added something for this, it's not checkbox but it's working, plz have a look and let me know if u have any feedback
https://ieve.yiilib.com/#/quick-table-ore

thx.

**Comment by Ledrap** [comment]
Much better/easier. 😊

Label is not fitting in button but that is just prettiness. 

L
