### ISSUE TITLE
左侧NAV导航栏，每次点击都会收起有点不方便。

### ISSUE THREAD

**Issue by yilumengxiang** [016/lm180_iEVE_Echoes#48]
单列图标和图表标题切换可以有，但是单看图表其实不知道是哪个入口。展开每次点击后又变成了单列图表，稍稍有点不方便。
另外多原矿计算那个模块貌似有BUG，好像我点一下精矿的input就会有报错。

**Comment by 016** [comment]
回复的有点晚，希望你别介意，实在太忙了， 导航的问题目前没有太好的解决方案，主要是针对手机用户 展开导航太占地方了。

另外一个问题请尝试使用chrome浏览器。

issue我关掉了， 如果有其他想法，欢迎随时追加。
