### ISSUE TITLE
造船计算器报错，全局中止

### ISSUE THREAD

**Issue by shinate** [016/lm180_iEVE_Echoes#49]
vue-file/ship.{chunk}.js

https://ieve.yiilib.com/#/build-ship > 选择船只 > 计算结果[填入矿物数量]: GLOBAL HALT

**Comment by 016** [comment]
@shinate 应该是 浏览器的问题， 换个浏览器试试吧， 如果还有问题 请重新打开 这个issue

推荐chrome...
