### ISSUE TITLE
reprocess ore Eve Echoes

### ISSUE THREAD

**Issue by Reany85** [016/lm180_iEVE_Echoes#54]
hedbergite 100 = 276 isogen (60% Efficiency) 

In game 275 isogen

please fix this

**Comment by 016** [comment]
hi @Reany85  morning, I just saw your email, I will reply here.

I can't direct change the value right now, with the follow reasons:
1. with 30% efficiency, the value is 138, in game, with my account
2. in the excel file that NE guys published, the value is 460(100% efficiency)
1+2: 138*2 = 276, 460*0.6 = 276

so I don't know why in game it's 275, can u test it again, and let me know the result?

thx for your feedback.

**Comment by Reany85** [comment]
may be it is a bug with game?))) i`ll try to send this bug to NE, 138*2=276   ----   30%eff*2=60%eff.  it is logical that there should be 276
thx

**Comment by 016** [comment]
@Reany85 you welcome, let me know if u have any new idea. :)
