### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by Cyno00** [016/lm180_iEVE_Echoes#6]
Hi, I speak English and Mandarin. I'm keen to help in translation.

你好，你们还需要中英翻译吗？

**Comment by 016** [comment]
Hi @Cyno00 留下联系方式把， 或者加下志愿者群？

**Comment by tosaddler** [comment]
I would also like to help with fully fixing the English translations. I do not speak Mandarin, however I am a fluent English speaker and can fix any mistranslations. I also was wondering if you would be willing to share the data that Exile provided you, as I am trying to get the wiki updated and it would speed things up a lot. Thanks!

**Comment by 016** [comment]
@tosaddler you are welcome to join the translate, but I am sry I can't share you any data, main reason is for some data I only have permission for use, I didn't get any permission for share it.

**Comment by 016** [comment]
@Cyno00 still interesting?

**Comment by Cyno00** [comment]
@016 Hey, sorry for the late reply, yes I am interested still.

**Comment by evilwarlock** [comment]
> Hi @Cyno00 留下联系方式把， 或者加下志愿者群？

求加志愿者群，我也可以帮忙

**Comment by 016** [comment]
@Cyno00 @evilwarlock welcome, an email address or write an email to yiilib.com@gmail.com thx

**Comment by 016** [comment]
first version English translate already finished by @evilwarlock
