### ISSUE TITLE
国际服和国服行星矿资源疑似不同

### ISSUE THREAD

**Issue by 502y** [016/lm180_iEVE_Echoes#61]
![CF@_N4{NOZ2H 8~ESIL3FLQ](https://user-images.githubusercontent.com/53784463/128448108-42c2c74c-9dc1-428d-ba16-c60cfe8908ae.png)

**Comment by 016** [comment]
官方程序bug 现在应该已经修复了。

**Comment by 502y** [comment]
好的，我再看看。感谢作者
