### ISSUE TITLE
this menu please don't hide

### ISSUE THREAD

**Issue by zhulankun** [016/lm180_iEVE_Echoes#62]
![image](https://user-images.githubusercontent.com/25838074/129994894-401e66a5-74f0-4f3a-ac47-7ae7a80a9e48.png)

**Comment by 502y** [comment]
兄弟，作者都回复过你了，没必要发好几遍吧。

**Comment by 016** [comment]
@zhulankun 最近比较忙，正在开发3.0版本的程序，所以没怎么在线，不好意思，我正面回应下这个问题吧
1. 最终的设计初衷是，为了方便手机用户，因为屏幕实在是太小了，所以自动隐藏了
2. 对于PC用户自动隐藏似乎不那么友好
3. 在未来的版本里会增加用户设置功能，允许用户自定义是否自动隐藏
4. 3.0版本开发完之后，才会增加相关功能，所以还需要等待。
