### ISSUE TITLE
Floating point precision issues

### ISSUE THREAD

**Issue by mafficraft** [016/lm180_iEVE_Echoes#7]
Most fields don't put out round numbers, but instead results in accurate but weird looking numbers. 
Example of this on the ship build calculator:
![grafik](https://user-images.githubusercontent.com/16704657/90763994-f0976d80-e2e7-11ea-8e1c-404faaabbded.png)

This could be alleviated by rounding these numbers to one decimal place, or just round them up to whole numbers entirely...

Thanks for the great project!

**Comment by 016** [comment]
Hey @mafficraft , thx for the feedback, I just fixed it, try again when u have time.
